name: Code Review

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
  # FOR TESTING
  push:
    branches:
      - EC-382-azure-pipe-migration
      
jobs:
  js_code_review:
    uses: pagopa/dx/.github/workflows/js_code_review.yaml@main
    name: Code Review
    secrets: inherit