
name: Release Infrastructure

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "infra/resources/**"

jobs:
  infra_release:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@5ed1c677fa7b4c59f3f3bcdc9cadaef0d6e1f34d # main
    name: Release Infrastructure
    secrets: inherit
    with:
      environment: prod
      base_path: infra/resources
      use_private_agent: false
